### ISSUE TITLE
Is it a bug?

### ISSUE THREAD

**Issue by housx** [daenny/collvoid#2]
Hi,Daniel Claes:
   I am loking at the code,and have some puzzled to ask you. 
   There is  a function A define as "size_t linearProgram2(const std::vector<Line> &lines, float radius, const Vector2 &optVelocity, bool dirOpt,Vector2 &result);".

   But the A is called by the function B"void Agent::computeOrcaVelocity" like below:
  {
     .................................
     size_t line_fail = linearProgram2(orca_lines_, max_speed_x_, pref_velocity, false, new_velocity_);
   }

The second param  'float radius' is cover by 'max_speed_x_',is it a bug or just the param's name is inappropriate.

Thank you !

**Comment by daenny** [comment]
Hi, sorry for the late reply. This comes from the official ORCA implementation. They approximate the achievable speeds by a circle, i.e. the robot can move in all directions equally fast. This is the radius meant here. So that is why it is max_speed_x.
